[workspace]
members = ["crates/simba"]

[workspace.package]
version = "0.2.0"
edition = "2024_07"
cairo-version = "2.19.4"
authors = ["bal7hazar"]
license = "MIT"
repository = "https://github.com/bal7hazar/simba-cairo"
keywords = ["math", "scalar", "fixed-point", "linear-algebra", "gamedev"]

[workspace.dependencies]
snforge_std = "0.61.0"
assert_macros = "2.19.4"

[workspace.tool.fmt]
sort-module-level-items = true
max-line-length = 100

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
