[package]
name = "simba_testing"
description = "Test and gas-benchmark helpers (not published)."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
publish = false

[dependencies]

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
